apiVersion: v1
kind: Service
metadata:
  name: contact-delete-service
  namespace: messaging
spec:
  type: LoadBalancer
  selector:
    app: contact-delete
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080