apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-query-deployment
  namespace: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-query
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: contact-query
    spec:
      containers:
        - name: contact-query-ms
          image: oh20/contactmicroservice-query:latest
          ports:
            - containerPort: 8080