apiVersion: v1
kind: Service
metadata:
  name: contact-query-service
  namespace: messaging  # Mesmo namespace do RabbitMQ
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "MC_Az-lab_labaks_westus3"
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # External LB
    service.beta.kubernetes.io/azure-pip-name: "aks-static-ip"
spec:
  type: LoadBalancer
  loadBalancerIP: 4.227.111.249
  selector:
    app: contact-query
  ports:
    - name: http
      protocol: TCP
      port: 80          # Porta externa
      targetPort: 8080  # Porta do container
  sessionAffinity: None