apiVersion: v1
kind: Service
metadata:
  name: dbconsumer-service
  namespace: messaging
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "MC_Az-lab_labaks_westus3"
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # External LB
    service.beta.kubernetes.io/azure-pip-name: "aks-dbconsumer-ip"
spec:
  type: LoadBalancer
  loadBalancerIP: 4.227.109.110  # IP dedicado para o DBConsumer
  selector:
    app: dbconsumer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  sessionAffinity: None