name: CI/CD Pipeline - Contact Microservices

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

env:
  REGISTRY: oh20
  AKS_CLUSTER: labaks
  AKS_RESOURCE_GROUP: Az-lab
  AKS_NAMESPACE: messaging
  DOTNET_VERSION: '8.0.x'

jobs:
  # Job de Build e Testes de todos os serviços
  build-and-test:
    name: Build e Test de todos os serviços
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build all projects
      run: |
        dotnet build --configuration Release --no-restore
        echo "✅ Build concluido com sucesso"

    # Executar todos os testes (incluindo testes com banco em memória)
    - name: Run tests for ContactCreateUpdateService
      run: dotnet test ./ContactCreateUpdateService.Tests/ContactCreateUpdateService.Tests.csproj --no-build --verbosity normal

    - name: Run tests for ContactQueryService
      run: dotnet test ./ContactQueryService.Tests/ContactQueryService.Tests.csproj --no-build --verbosity normal

    - name: Run tests for DBConsumerService
      run: dotnet test ./DBConsumer.Tests/DBConsumer.Tests.csproj --no-build --verbosity normal

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'

    - name: Test Summary
      if: always()
      run: |
        echo "📊 RESUMO DOS TESTES"
        echo "==================="
        echo "🔖 Commit: ${{ github.sha }}"
        echo "📅 Executado em: $(date)"
        echo "✅ Todos os testes executados com sucesso!"
        echo ""
        echo "🧪 Testes executados:"
        echo "- ContactCreateUpdateService Tests"
        echo "- ContactQueryService Tests" 
        echo "- DBConsumer Tests"
        echo ""
        echo "💾 Banco de dados: In-Memory (Entity Framework)"
        echo "⚡ Performance: Rápida e confiável"

  # Job de Build das Imagens Docker
  build-images:
    name: Build das Imagens Docker
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configurar tag da imagem
      id: image-tag
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "tag=main-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        else
          echo "tag=develop-${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
        fi

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e push ContactCreate
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./contactCreateDockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/contactmicroservice-create:${{ steps.image-tag.outputs.tag }}
          ${{ env.REGISTRY }}/contactmicroservice-create:latest

    - name: Build e push ContactDelete
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./contactDeleteDockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/contactmicroservice-delete:${{ steps.image-tag.outputs.tag }}
          ${{ env.REGISTRY }}/contactmicroservice-delete:latest

    - name: Build e push ContactQuery
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./contactQueryDockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/contactmicroservice-query:${{ steps.image-tag.outputs.tag }}
          ${{ env.REGISTRY }}/contactmicroservice-query:latest

    - name: Build e push DBConsumer
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dbConsumerDockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/contactmicroservice-dbconsumer:${{ steps.image-tag.outputs.tag }}
          ${{ env.REGISTRY }}/contactmicroservice-dbconsumer:latest

    - name: Resumo da build Docker
      run: |
        echo "🐳 Imagens Docker criadas e enviadas com sucesso!"
        echo "📝 tag da imagem: ${{ steps.image-tag.outputs.tag }}"

  # Job de Deploy no AKS
  deploy:
    name: Deploy no AKS
    runs-on: ubuntu-latest
    needs: [build-and-test, build-images]
    if: github.ref == 'refs/heads/main'
    environment: ${{ github.event.inputs.environment || 'production' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Configurar kubectl
      uses: azure/setup-kubectl@v3

    - name: Obter credenciais do AKS
      run: |
        az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}
        echo "✅ AKS credentials configured"

    - name: Aplicar manifestos K8s
      run: |
        for dir in ./K8s/*/
        do
          echo "Aplicando manifestos em $dir"
          kubectl apply -f "$dir"
        done

    - name: Deploy de todos os serviços
      run: |
        IMAGE_TAG="${{ needs.build-images.outputs.image-tag }}"
        echo "🚀 Deploy com tag: $IMAGE_TAG"
        
        # Deploy ContactCreate
        kubectl set image deployment/create-contact-deployment \
          create-contact-ms=${{ env.REGISTRY }}/contactmicroservice-create:$IMAGE_TAG \
          -n ${{ env.AKS_NAMESPACE }}
        
        # Deploy ContactDelete
        kubectl set image deployment/contact-delete-deployment \
          contact-delete-ms=${{ env.REGISTRY }}/contactmicroservice-delete:$IMAGE_TAG \
          -n ${{ env.AKS_NAMESPACE }}
        
        # Deploy ContactQuery
        kubectl set image deployment/contact-query-deployment \
          contact-query-ms=${{ env.REGISTRY }}/contactmicroservice-query:$IMAGE_TAG \
          -n ${{ env.AKS_NAMESPACE }}
        
        # Deploy DBConsumer
        kubectl set image deployment/dbconsumer \
          dbconsumer=${{ env.REGISTRY }}/contactmicroservice-dbconsumer:$IMAGE_TAG \
          -n ${{ env.AKS_NAMESPACE }}
        
        echo "✅ Todos os serviços atualizados"
      
    - name: Verificar deployments
      run: |
        echo "🔍 Verificando deployments..."
        
        kubectl rollout status deployment/create-contact-deployment -n ${{ env.AKS_NAMESPACE }} --timeout=300s
        kubectl rollout status deployment/contact-delete-deployment -n ${{ env.AKS_NAMESPACE }} --timeout=300s
        kubectl rollout status deployment/contact-query-deployment -n ${{ env.AKS_NAMESPACE }} --timeout=300s
        kubectl rollout status deployment/dbconsumer -n ${{ env.AKS_NAMESPACE }} --timeout=300s
        
        echo "✅ Todos os deployments verificados com sucesso"

    - name: Executar health checks
      run: |
        echo "🏥 Executando health checks..."
        sleep 30
        
        # Test ContactQuery (IP fixo: 4.227.111.249)
        echo "Testando ContactQuery service..."
        curl -f http://4.227.111.249/health || echo "⚠️ ContactQuery health check falhou"
        
        # Test DBConsumer (IP fixo: 4.227.109.110)
        echo "Testando DBConsumer service..."
        curl -f http://4.227.109.110/health || echo "⚠️ DBConsumer health check falhou"
        
        echo "✅ Health checks concluido"

    - name: Resumo do Deployment
      run: |
        echo "📊 RESUMO DO DEPLOYMENT"
        echo "====================="
        echo "🔖 Commit: ${{ github.sha }}"
        echo "🏷️  Image Tag: ${{ needs.build-images.outputs.image-tag }}"
        echo "🌍 Environment: ${{ github.event.inputs.environment || 'production' }}"
        echo "📅 Deployado em: $(date)"
        echo ""
        echo "🎯 Status dos Serviços:"
        kubectl get pods -n ${{ env.AKS_NAMESPACE }} -o wide
        echo ""
        echo "🌐 Endpoints dos Serviços:"
        kubectl get svc -n ${{ env.AKS_NAMESPACE }}
        echo ""
        echo "🎉 Deployment concluido com sucesso!"

  # Job de Notificação (opcional)
  notify:
    name: Enviar Notificação
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    
    steps:
    - name: Notificar status do deployment
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Deployment concluido com sucesso!"
          # Aqui você pode adicionar notificação para Slack, Teams, etc.
        else
          echo "❌ Deployment falhou!"
          # Aqui você pode adicionar notificação de falha
        fi